### ISSUE TITLE
Izradjen projekat iz racunarske grafike

### ISSUE THREAD

**Issue by mi15405** [MATF-RG17/RG057-lift#1]
Dodao bih razlog zbog kog sam koristio operator new u nekoliko situacija i spreman sam da razumem zasto to ne bi trebalo da radim.

Loptice iscrtava objekat koji ih poseduje, u mom slucaju to mogu biti spratovi ili lift. Problem nastaje kada se loptica prebacuje sa jednog objekta na drugi. Jedna opcija je bila da se loptica klonira u objektu u koji treba da predje i da se izbrise iz starog objekta, a druga opcija je bila da se samo prosledi pokazivac na lopticu (bez ikakvog kopiranja) sto zahteva da bude na heap-u.

Iako loptica nema puno polja, intuitivnije mi je bilo da prosledjujem pokazivac.

**Comment by ivan-cukic-matf** [comment]
U takvim situacijama koristite std::unique_ptr i std::make_unique. Ali, ovo je nešto što ćete učiti na kursu C++-a.
